# Dataset Loading

The dataset is downloaded from Kaggle and stored locally in the `data/raw/` folder.

The file used is `3A2M.csv`, which contains a large collection of recipes.

In [ ]:
import sys
from pathlib import Path

sys.path.append(str(Path().resolve().parent))

## 1. Check raw dataset file

Before loading the dataset, we verify that the raw CSV file exists in the expected folder.

In [8]:
from src.cookmate.utils.config import RAW_DATA_FILE

print(RAW_DATA_FILE)
print(RAW_DATA_FILE.exists())

C:\Users\aless\Documents\cookmate-ai\data\raw\3A2M.csv
True

## 3. Load a subset of the dataset

The full dataset is too large, so we load only a small portion for initial exploration.

In [10]:
import pandas as pd 
from src.cookmate.utils.config import RAW_DATA_FILE

df = pd.read_csv(RAW_DATA_FILE, nrows=5000)

print(df.shape)
df.head()

(5000, 6)

,Unnamed: 0,title,directions,NER,genre,label
0,0,Reeses Cups(Candy),"[""Combine first four ingredients and press in ...","[""peanut butter"", ""graham cracker crumbs"", ""bu...",drinks,2
1,1,Rhubarb Coffee Cake,"[""Cream sugar and butter."", ""Add egg and beat ...","[""sugar"", ""butter"", ""egg"", ""buttermilk"", ""flou...",drinks,2
2,2,Quick Barbecue Wings,"[""Clean wings."", ""Flour and fry until done."", ...","[""chicken"", ""flour"", ""barbecue sauce""]",nonveg,3
3,3,Chocolate Frango Mints,"[""Mix ingredients together for 5 minutes."", ""S...","[""cake mix"", ""chocolate fudge pudding"", ""sour ...",drinks,2
4,4,Corral Barbecued Beef Steak Strips,"[""Brown strips in cooking oil."", ""Pour off dri...","[""long"", ""cooking oil"", ""tomato sauce"", ""water...",drinks,2

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5000 non-null   int64
 1   title       5000 non-null   object
 2   directions  5000 non-null   object
 3   NER         5000 non-null   object
 4   genre       5000 non-null   object
 5   label       5000 non-null   int64
dtypes: int64(2), object(4)
memory usage: 234.5+ KB

In [12]:
df.columns

Index(['Unnamed: 0', 'title', 'directions', 'NER', 'genre', 'label'], dtype='object')

In [13]:
df.sample(5)

,Unnamed: 0,title,directions,NER,genre,label
3813,3813,Punch Bowl Cake,"[""Bake cake as directed; split to make 3 layer...","[""cake"", ""O"", ""frozen strawberries"", ""strawber...",drinks,2
3926,3926,Lemon And Rosemary Chicken,"[""Sprinkle chicken with black pepper and garli...","[""chicken breasts"", ""lemon juice"", ""fresh grou...",drinks,2
2254,2254,Chewy Chocolate Cookies,"[""In large bowl, blend sugar, margarine and ch...","[""sugar"", ""butter"", ""unsweetened chocolate"", ""...",drinks,2
4370,4370,Oatmeal Cookies,"[""Mix flour with baking soda and set aside."", ...","[""flour"", ""baking soda"", ""butter"", ""sugar"", ""b...",cereal,6
675,675,Apple Roll(With Best Biscuit Mix),"[""Peel, core and fine dice the apples or \""coa...","[""tart apples"", ""sugar"", ""water"", ""batch""]",vegetables,4

## 4. Select relevant columns

We keep only the fields necessary for the project:
- title
- directions (instructions)
- NER (ingredients)
- genre (we can use for filter)

Other columns are dropped.

In [14]:
df = df[["title", "directions", "NER", "genre"]]

In [15]:
df.head()

,title,directions,NER,genre
0,Reeses Cups(Candy),"[""Combine first four ingredients and press in ...","[""peanut butter"", ""graham cracker crumbs"", ""bu...",drinks
1,Rhubarb Coffee Cake,"[""Cream sugar and butter."", ""Add egg and beat ...","[""sugar"", ""butter"", ""egg"", ""buttermilk"", ""flou...",drinks
2,Quick Barbecue Wings,"[""Clean wings."", ""Flour and fry until done."", ...","[""chicken"", ""flour"", ""barbecue sauce""]",nonveg
3,Chocolate Frango Mints,"[""Mix ingredients together for 5 minutes."", ""S...","[""cake mix"", ""chocolate fudge pudding"", ""sour ...",drinks
4,Corral Barbecued Beef Steak Strips,"[""Brown strips in cooking oil."", ""Pour off dri...","[""long"", ""cooking oil"", ""tomato sauce"", ""water...",drinks

## 5. Explore genre values

Analyze the unique valors in "genre" column to understand how recepies are categorized.

In [16]:
df["genre"].unique()

array(['drinks', 'nonveg', 'vegetables', 'bakery', 'cereal', 'fastfood',
       'meal', 'fusion', 'sides'], dtype=object)

In [17]:
df["genre"].value_counts()

genre
drinks        1616
vegetables    1430
cereal         884
nonveg         708
fastfood       265
bakery          46
fusion          35
meal            14
sides            2
Name: count, dtype: int64

## 6. Rename columns

We rename columns to make the dataset clearer and consistent with our application.

In [19]:
df = df.rename(columns={
    "title": "title",
    "directions": "instructions",
    "NER": "ingredients"
})
df

,title,instructions,ingredients,genre
0,Reeses Cups(Candy),"[""Combine first four ingredients and press in ...","[""peanut butter"", ""graham cracker crumbs"", ""bu...",drinks
1,Rhubarb Coffee Cake,"[""Cream sugar and butter."", ""Add egg and beat ...","[""sugar"", ""butter"", ""egg"", ""buttermilk"", ""flou...",drinks
2,Quick Barbecue Wings,"[""Clean wings."", ""Flour and fry until done."", ...","[""chicken"", ""flour"", ""barbecue sauce""]",nonveg
3,Chocolate Frango Mints,"[""Mix ingredients together for 5 minutes."", ""S...","[""cake mix"", ""chocolate fudge pudding"", ""sour ...",drinks
4,Corral Barbecued Beef Steak Strips,"[""Brown strips in cooking oil."", ""Pour off dri...","[""long"", ""cooking oil"", ""tomato sauce"", ""water...",drinks
...,...,...,...,...
4995,Ham And Cheese Ball,"[""Soften cheeses at room temperature or in mic...","[""regular"", ""Cheddar cheese spread"", ""ham""]",nonveg
4996,French Fried Onion Rings,"[""Combine first 5 ingredients in a large bowl....","[""flour"", ""eggs"", ""milk"", ""baking powder"", ""sa...",vegetables
4997,Chocolate Snowballs,"[""Cream oleo and sugar; beat in egg."", ""Add ch...","[""flour"", ""baking powder"", ""salt"", ""oleo"", ""su...",drinks
4998,Lo-Cal Corn Meal Muffins,"[""Mix all ingredients and pour into 4 muffin t...","[""meal"", ""mayonnaise"", ""buttermilk""]",cereal
4999,Venison Pepper Steak And Rice,"[""Cut meat into thin strips or small pieces."",...","[""venison"", ""vegetable oil"", ""tomato"", ""green ...",cereal

## 7. Basic filtering by genre

We remove non-relevant categories such as drinks, fast food, and fusion and focus on actual food recipes.

In [21]:
df = df[df["genre"] != "drinks"]
df = df[df["genre"] != "fastfood"]
df = df[df["genre"] != "fusion"]
df["genre"].value_counts()

genre
vegetables    1430
cereal         884
nonveg         708
bakery          46
meal            14
sides            2
Name: count, dtype: int64

## 8. Convert string fields in lists

The "ingredients" and "instructions" fields are stored as strings, we convert them into list for easier processing.

In [22]:
import ast
df["ingredients"] = df["ingredients"].apply(ast.literal_eval)
df["instructions"] = df["instructions"].apply(ast.literal_eval)

In [23]:
type(df["ingredients"].iloc[0])

list

In [24]:
df["ingredients"].iloc[0]

['chicken', 'flour', 'barbecue sauce']

## 9. Filter recipes by ingredients

We filter recipes based on relevant ingredients to keep only useful and realistic recipes.
The goal is to keep and use as much europan recipe more like Italian recepies.

In [25]:
italian_keywords = [
    "pasta", "tomato", "olive oil", "garlic",
    "basil", "parmesan", "mozzarella",
    "cheese", "chicken", "beef", "onion"
]

def has_relevant_ingredient(ingredients):
    ingredients = [i.lower() for i in ingredients]
    return any(
        keyword in ingredient
        for ingredient in ingredients
        for keyword in italian_keywords
    )
df = df[df["ingredients"].apply(has_relevant_ingredient)]

In [26]:
df.shape
df.head()

,title,instructions,ingredients,genre
2,Quick Barbecue Wings,"[Clean wings., Flour and fry until done., Plac...","[chicken, flour, barbecue sauce]",nonveg
6,Potato And Cheese Pie,"[Beat eggs, salt and pepper until well blended...","[eggs, salt, pepper, potatoes, Cheddar cheese,...",vegetables
8,Pineapple Nut Pie,[Cream the cream cheese; add the milk and beat...,"[cream cheese, condensed milk, pineapple, nuts...",vegetables
9,Crustless Vegetable Ham Pie,"[Preheat oven to 325°., In large frying pan, m...","[butter, mushrooms, garlic, zucchini, onion, e...",vegetables
10,Barbecue Noodle Cheese Bake,"[Cook hamburg and crumble., Add Manwich., Spra...","[Manwich, hamburg, American cheese, noodles]",bakery

## Experimental filtering (European-style recipes)

We apply a stricter filtering rule based on ingredient similarity to European cuisine.

A recipe is kept only if most of its ingredients match a predefined keyword list.

In [31]:
import pandas as pd
import ast
import json
from src.cookmate.utils.config import RAW_DATA_FILE, PROCESSED_DATA_DIR

chunk_size = 5000

clean_data = []
recipe_counter = 0

# expanded keyword list (european-style)
european_keywords = [
    "pasta", "spaghetti", "penne",
    "rice", "risotto",
    "potato", "potatoes",
    "tomato", "tomato sauce",
    "olive oil", "butter",
    "garlic", "onion",
    "carrot", "celery",
    "basil", "parsley",
    "cheese", "parmesan", "mozzarella", "ricotta",
    "milk", "cream",
    "egg", "eggs",
    "chicken", "beef", "pork",
    "sausage", "ham",
    "flour", "bread"
]

def safe_eval(x):
    try:
        return ast.literal_eval(x)
    except:
        return []

def european_score(ingredients):
    ingredients = [i.lower() for i in ingredients]
    
    total = len(ingredients)
    if total == 0:
        return 0
    
    matches = sum(
        any(keyword in ingredient for keyword in european_keywords)
        for ingredient in ingredients
    )
    
    return matches / total  # percentage


for chunk in pd.read_csv(RAW_DATA_FILE, chunksize=chunk_size):
    
    # select columns
    chunk = chunk[["title", "directions", "NER", "genre"]]
    
    # rename
    chunk = chunk.rename(columns={
        "directions": "instructions",
        "NER": "ingredients"
    })
    
    # filter genre
    chunk = chunk[~chunk["genre"].isin(["drinks", "fastfood", "fusion"])]
    
    # convert
    chunk["ingredients"] = chunk["ingredients"].apply(safe_eval)
    chunk["instructions"] = chunk["instructions"].apply(safe_eval)
    
    # apply european filter (STRICT)
    chunk = chunk[chunk["ingredients"].apply(lambda x: european_score(x) >= 0.9)]
    
    # build dataset
    for _, row in chunk.iterrows():
        recipe = {
            "id": f"recipe_{recipe_counter}",
            "title": row["title"],
            "ingredients": row["ingredients"],
            "instructions": row["instructions"]
        }
        clean_data.append(recipe)
        recipe_counter += 1
        
        if len(clean_data) >= 2500:
            break
    
   # if len(clean_data) >= 2500:
       # break
len(clean_data)

<unknown>:1: SyntaxWarning: invalid escape sequence '\g'

2870

## Final dataset selection

We keep a high-quality subset of recipes.

## Save in Json

In [33]:
# when we have to performe the embeddings we will pass a string 
# so we add a text field in this stage so it will be easier later.

for recipe in clean_data:
    recipe["text"] = (
        f"Recipe: {recipe['title']}. "
        f"Ingredients: {', '.join(recipe['ingredients'])}. "
        f"Instructions: {' '.join(recipe['instructions'])}"
    )

# save JSON
import json
from src.cookmate.utils.config import PROCESSED_DATA_DIR

output_path = PROCESSED_DATA_DIR / "recipes_clean.json"

with open(output_path, "w") as f:
    json.dump(clean_data, f, indent=2)